name: Release
on:
  push:
    branches:
      - main
      - rc
      - beta
      - alpha
      - "*.x"

permissions:
  contents: write

jobs:
  get-next-version:
    uses: lenra-io/github-actions/.github/workflows/get-version.yml@main
    
  release:
    needs: [get-next-version]
    if: ${{ needs.get-next-version.outputs.will-release == 'true' }}
    uses: lenra-io/github-actions/.github/workflows/release.yml@main
