name: PHP test
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      # - uses: php-actions/composer@v6
      #   with:
      #     php-version: '8.2'
      - run: composer install
      - run: composer dump-autoload
      - run: ./vendor/bin/phpunit test
      # - uses: php-actions/phpunit@v3
      #   with:
      #     php-version: '8.2'
      #     args: test
