name: PHP test
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - run: composer install
      - run: composer dump-autoload
      - uses: php-actions/phpunit@v3
        with:
          args: test
